In [ ]:
# flask
import flask # 웹서버 기능 5000번 포트로 서비스

In [4]:
import matplotlib # 시각화 패키지
import numpy as np # 별칭 class
print(np.__version__) # 상위 오브젝트가 가진 속성
def pprint(arr): # ndarray: numpy의 기본 데이터 배열
    print("type:{}".format(type(arr)))
    print("shape:{}, dimension:{},dtype:{}".format(arr.shape,arr.ndim,arr.dtype))
    print("Array's Data: \n",arr)
    # 숫자의 디폴트는 int32
arr = [1.0,2.0,3.0] # 리스트
a = np.array([1,2,3]) # ndarray 생성함수 (매개변수:리스트)
pprint(a)

1.16.5
type:<class 'numpy.ndarray'>
shape:(3,), dimension:1,dtype:int32
Array's Data: 
 [1 2 3]


In [5]:
# 인스턴스상태
a = np.array([0,1,2,3,4,5,6,7,8,9]) # ndarray
print(id(a)) # python core 주소값 확인
print(a.size) # 데이터 개수
print(a.astype(np.float32)) # 데이터타입변경, numpy는 행중심, 동질적
print(a.dtype.itemsize*a.size) # 전체 메모리 사이즈(바이트)
# iterator for in range => list
a = np.arange(1000) # => ndarray
a

2472290444512
10
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
40


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [6]:
# ndarray초기화 함수들
print(np.zeros((3,4))) # 0
print(np.ones((2,3,4),dtype=np.int16)) # 1, 3차원 (면, 행, 열)
print(np.full((2,2),7))
print(np.eye(4)) # 대각행렬 identity
print(np.empty((4,2))) # 쓰레기값

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[7.56602523e-307 1.11258446e-306]
 [6.23059726e-307 8.45593934e-307]
 [4.89547485e-307 1.86921958e-306]
 [1.37959061e-306 5.11766988e-307]]


In [8]:
a = np.arange(0,100,10) # ndarray
indices = [1,5,-1] # 리스트
print(indices)
b = a[indices]
print(a)
print(b)

[1, 5, -1]
[ 0 10 20 30 40 50 60 70 80 90]
[10 50 90]


In [11]:
a = np.arange(11,36) # 1차원
print(a)
a.shape = (5,5) # 정상모양을 갖춘 개수 ( R과 동일 )
print(a)
print(type(a))
print(a.dtype)
print(a.size)
print(a.shape) # 차수 (5,5)
print(a.ndim) # 2차원
print(a.nbytes) # 100바이트 = 25*4
print(a.strides) # (20,4) # 다음열의 데이터는 몇 바잍트를 건너뛰어야 하는가
                          # 다음 행은 몇바이트를 건너뛰어야 하는가

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
<class 'numpy.ndarray'>
int32
25
(5, 5)
2
100
(20, 4)


In [13]:
arr = np.arange(10)
print(type(arr))
print(arr)
print(arr[5])
print(arr[5:8]) # 마지막 불포함
arr[5:8]=12 # 데이터 update
print(arr[1:6])

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 1  2  3  4 12]


In [14]:
# numpy 첨자생략불가[,4]
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[0]) # 행우선 : 행
print(arr2d[0][2])
print(arr2d[0,2])
print(arr2d[:2]) # 0,1행
print(arr2d[:2,1:]) # 끝까지
print(arr2d[: ,:2]) # 모든행
print(arr2d[2,:1])
arr2d[:2,:1]=0
arr2d[:2,:1]=0
print(arr2d)

[1 2 3]
3
3
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[[1 2]
 [4 5]
 [7 8]]
[7]
[[0 2 3]
 [0 5 6]
 [7 8 9]]


In [15]:
# 실제 저장은 일렬로 사람이 데이터를 다루는 것은 입체로
# 행렬연산에서 앞의 행렬열수와 뒤의 헹랼의 헹수를 일치 시켜야 행렬 곱이 가능
# 행렬곱에서 행렬 앞뒤로 바꾸면 안됨
print("스트라이드의 값", np.ones((3,4,5),dtype=np.float64).strides) 
# (면, 행, 열) # 4행 5열의 데이터가 3면있는 것
# (160, 40, 8) # 단일 데이터 float64 : 8바이트

스트라이드의 값 (160, 40, 8)


In [20]:
# 문제
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 2, 2, 3
print("첫면은 ", arr3d[0]) # 0번 면
print("첫면 첫행은 ",arr3d[0][0])
print("첫면 첫행 첫요소는 ", arr3d[0][0][0])

# 8을 출력하시오
arr3d[1][0][1]
#12를 출력하시오
arr3d[1][1][2]

첫면은  [[1 2 3]
 [4 5 6]]
첫면 첫행은  [1 2 3]
첫면 첫행 첫요소는  1


12

In [21]:
old_values = arr3d
arr3d[0] = 42
print("값의 변경후")
print(arr3d)
print("이전 값으로 복구")
arr3d = old_values
print(arr3d)

값의 변경후
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
이전 값으로 복구
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


In [22]:
old_values = arr3d
arr3d[0] = 42
print("값의 변경후")
print(arr3d)
print("이전 값으로 복구")
arr3d = old_values
print(arr3d)

값의 변경후
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
이전 값으로 복구
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


In [25]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
old_values = arr3d.copy()
arr3d[0] = 42
print("값의 변경후")
print(arr3d)
print("이전 값으로 복구")
arr3d = old_values
print(arr3d)

값의 변경후
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
이전 값으로 복구
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [23]:
Z = np.arange(36)
print(Z)
Z = Z.reshape(6,6)
reshape2 = Z.reshape((2,3,6))
print(reshape2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [24]:
arr=np.arange(32).reshape((8,4))
print(arr)
print(arr[[1,5,7,2]]) # 행중심
print(arr[[-1,-5,-7,-2]]) # 거꾸로 인덱싱
print(arr[[1,5,7,2],[0,3,1,2]])
# fancy 인덱싱
print(arr[[1,2,5,7],][:,[0,1,2,3]])
print(arr[[1,5,7,2]][:,[0,3,1,2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[[28 29 30 31]
 [12 13 14 15]
 [ 4  5  6  7]
 [24 25 26 27]]
[ 4 23 29 10]
[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [28 29 30 31]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [27]:
arr=[]
for i in range(6) :
    ad=[]
    for j in range(6) :
        ad.append( i*10 + j )
    arr.append(ad)
print(arr)
arr=np.array(arr)

[[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]]


In [38]:
print("주황색",arr[[0,1,2,3,4],[1,2,3,4,5]])

주황색 [ 1 12 23 34 45]


In [40]:
print("빨강색",arr[[0,2,5],2])
print("하늘색",arr[3:6][:,[0,2,5]])

빨강색 [ 2 22 52]
하늘색 [[30 32 35]
 [40 42 45]
 [50 52 55]]


In [53]:
print("빨강",arr[: ,2])
print("주황",arr[0,[3,4]])
print("연두",arr[[2,4]][:,[0,2,4]])
print("하늘",arr[4:][:,[4,5]])

빨강 [ 2 12 22 32 42 52]
주황 [3 4]
연두 [[20 22 24]
 [40 42 44]]
하늘 [[44 45]
 [54 55]]


In [56]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
# [1,2,3]
# [4,5,6]
# [7,8,9]
# [10,11,12]
v=np.array([1,0,1])
print("타일출력")
vv=np.tile(v,(4,1))
print(vv)
y = x+vv # 4X3 배열연산=>요소별 연산
print(y)
# 배열연산 : 양쪽 차원이 일치해야함
x+v # 4X3, 1X3 broadcasting
        #  1X3을 자동으로 4번 반복
    # 단 하나의 조건 (행이나 열)의 수가 맞아야함
x+3

타일출력
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [65]:
x=np.arange(6).reshape((3,2))
print(x)
# 거듭제곱 ( 행열곱 )
x@x # 앞의 행렬 열수와 뒤의 행렬의 행수가 일치해야함
# (3*2) (3*2)
# 전치행렬을 사용하면 가능해진다.

[[0 1]
 [2 3]
 [4 5]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [67]:
#print(x.T)
x@x.T
print(np.transpose(x))

[[0 2 4]
 [1 3 5]]


In [68]:
arr = np.arange(24).reshape((2,3,4)) # 0,1,2
print(arr)
# 3*2*4
print(arr.transpose((1,0,2))) # 면과 행의 위치를 바꿔라
# 2*4*3
print(arr.transpose((0,2,1)))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


In [71]:
# Boolean indexing (True/False)
# 문자열은 대소문자 구분
names = np.array(['Seoul','Daejun','chungju','seoul','chungju','Daejun','Daejun'])
data=np.random.randn(7,4)
print(names=='Seoul') # 1,0,0,0,0,0,0
print(data[names=='Seoul']) # 0번행
print(data[names=='Seoul',2:])
print(data[names=='Seoul',3])
print(names != 'Seoul') # 0,1,1,1,1,1,1
print(~(names=='Seoul'))
mask = (names == 'Seoul') | (names=='chungju')
print(mask)
print(data[mask])

[ True False False False False False False]
[[ 2.01590629 -0.02681004  0.67496553  0.97447086]]
[[0.67496553 0.97447086]]
[0.97447086]
[False  True  True  True  True  True  True]
[False  True  True  True  True  True  True]
[ True False  True False  True False False]
[[ 2.01590629 -0.02681004  0.67496553  0.97447086]
 [ 1.28078016  1.62171342  0.26593703  1.4398506 ]
 [-1.15054151  2.5867194   0.96784795  1.26920412]]


In [74]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True, False, True, True, False])
print(zip(xarr,yarr,cond)) # 요소별로 데이터를 묶음, zip : 고유포맷
print(list(zip(xarr,yarr,cond)))

result = [(x if c else y) for x,y,c in zip(xarr, yarr, cond)] # 3 항연산자
print("result = ",result)

result = np.where(cond, xarr, yarr)
print(result)

arr = np.random.randn(4,4)
print(arr)
print(np.where(arr>0, 2, -2))

[(1.1, 2.1, True), (1.2, 2.2, False), (1.3, 2.3, True), (1.4, 2.4, True), (1.5, 2.5, False)]
result =  [1.1, 2.2, 1.3, 1.4, 2.5]
[1.1 2.2 1.3 1.4 2.5]
[[-0.05536481 -0.02581771  1.3437015  -1.13929098]
 [-0.20666958  0.593613   -0.15184825 -1.0566624 ]
 [-0.46668269  1.12268849  0.25628894  0.70241769]
 [ 0.4867363  -1.63667757  1.01667455  2.17319051]]
[[-2 -2  2 -2]
 [-2  2 -2 -2]
 [-2  2  2  2]
 [ 2 -2  2  2]]


문제 ) 다음 데이터를 이용하여 두개다 참일 때는 0, cond1이 참일 때는 1, cond2가 참일 때는 2
그 외일 때는 3으로 처리하여 출력하도록 하시오. (0,1,2,3)
- 조건 4
- where 3

In [84]:
result = []
cond1 = np.array([1,0,1,1,0,0,1],dtype=bool)
cond2 = np.array([0,1,1,1,0,1,1],dtype=bool)

In [85]:
for i in range(len(cond1)):
    if(cond1[i] and cond2[i]):
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else: 
        result.append(3)
print("조건문", result)

result = np.where(cond1&cond2,0,
                  np.where(cond1,1,
                           np.where(cond2,2,3)))
print("3항연산자",result)

result = 1*(cond1&~cond2) + 2*(cond2&~cond1) + 3*~(cond1|cond2)
print("수식을 이용한",result)

조건문 [1, 2, 0, 0, 3, 2, 0]
3항연산자 [1 2 0 0 3 2 0]
수식을 이용한 [1 2 0 0 3 2 0]


In [86]:
# 소정' S 방식
re2 = np.where(cond2,2,3)
re1 = np.where(cond1,1,re2)
result = np.where(cond1&cond2,0,re1)

print(result)

[1 2 0 0 3 2 0]


In [87]:
x = np.arange(1,10001)
y = np.arange(10001,20001)

z=np.zeros_like(x) # 다른 행렬과 같은 사이즈로 초기화
for i in range(10000):
    z[i] = x[i]+y[i]

In [90]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
print(np.all( a==b )) # 전체가 참일 때 참
print(np.any(a==b)) # 하나라도 참이면 참
print(np.exp(a)) # 지수함수 ( 자연대수 : 2.718)

False
True
[ 2.71828183  7.3890561  20.08553692 54.59815003]


# 선형대수 : 선형으로 해결하자. => 비선형도 잘게 나누면 선형

# 행렬의 종류
- 정방행렬 : 정사각형 ( 행과 열수가 같은 행렬 )
- 대칭행렬 : 우상단과 좌하단 같은것
- 대각행렬 : scale을 변화시키는 요소
- 단위행렬( identity ) : 행렬곱의 항등원, 행렬과 역행렬을 곱하면 단위행렬
- 역행렬 : 행렬의 나눗셈을 위해 구해서 곱해지는 행렬 ( 정방행렬만 가능 )
- 특이행렬 : 역행렬이 없는 행렬
- 직교행렬 : 축의 정직교, 각축간의 내적이 0인 행렬
- 정방행렬이면서 대칭행렬 : 공분산행렬, 상관계수행렬, 거리행렬
- 공분산 : 두수간의 관계 ((한수-평균) * (다른수-평균))/(n-1)
- 상관계수(표준화 -1~1) : 공분산 / 표준편차의 곱

In [91]:
import numpy as np
F1 = np.array([[1,2],[3,4]]) # 2x2
F2 = np.array([[2,2],[2,2]]) # 2x2

print(F1)
print(F2)

print(F1+F2) # 요소끼리
print(F1*F2) # 요소끼리

print(F1@F2)  # 두 벡터의 사이각을 구해서 다른 벡터를 생성
#  F1     F2  # 행열곱도 내적
# 1,2    2,2     6, 6            
# 3,4    2,2    14,14
# 만약 (2*2) (2*3) 행렬곱을 수행 => 차원확장

[[1 2]
 [3 4]]
[[2 2]
 [2 2]]
[[3 4]
 [5 6]]
[[2 4]
 [6 8]]
[[ 6  6]
 [14 14]]


# 방정식의 해
2* x1 + x2 -2* x3 = -3
3* x1 + x3 = 5
x1 + x2 - x3 = -2

In [100]:
A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
print(A)
b = np.transpose(np.array([[-3,5,-2]]))
print(b)

[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]
[[-3]
 [ 5]
 [-2]]


In [104]:
x = np.linalg.solve(A,b) # A의 역행렬을 구해서 b와 곱해줌
print(x)

[[ 1.]
 [-1.]
 [ 2.]]


In [107]:
np.dot(np.linalg.inv(A),b) # 행렬곱

array([[ 1.],
       [-1.],
       [ 2.]])

In [103]:
np.linalg.inv(A)@b # 왜 역행렬을 구해야 하는가?
                   # 행렬은 나눗셈이 없어서 역행렬을 곱해서 계산한다.

array([[ 1.],
       [-1.],
       [ 2.]])

In [105]:
# 검산
2*1 + (-1) -2*2

-3

In [108]:
a = np.array([0,1,0]) # x축
b = np.array([1,0,0]) # y축
res = np.dot(a,b) # 내적 사이각
print(res)

0


In [110]:
print(np.linalg.norm(a)) # 벡터의 크기
print(np.linalg.norm(b))
print(np.linalg.norm(a)*np.linalg.norm(b))
rad = res/ (np.linalg.norm(a)*np.linalg.norm(b)) # cos(theta)
print("cos theta", rad)
print(np.arccos(rad)) # theta 값을 구함
print(np.degrees(np.arccos(rad))) # 사람이 알아보는 각도로 표현

1.0
1.0
1.0
cos theta 0.0
1.5707963267948966
90.0


In [111]:
x = np.array([[1,2],[3,4]])
y = np.linalg.inv(x)
print(x)
print(y)
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


# 다음 방정식의 해를 구하고 검산하시오.

x + y + z = 6
2y + 5z = -4
2x + 5y -z = 27

In [3]:
import numpy as np
B = np.array([[1,1,1],[0,2,5],[2,5,-1]])
print(B)
a = np.transpose(np.array([[6,-4,27]]))
print(a)

[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
[[ 6]
 [-4]
 [27]]


In [10]:
ans1 = np.linalg.solve(B,a)
print("풀이법1")
print(ans1)
ans2 = np.dot(np.linalg.inv(B),a)
print("풀이법2")
print(ans2)
ans3 = np.linalg.inv(B)@a
print("풀이법3")
print(ans3)

풀이법1
[[ 5.]
 [ 3.]
 [-2.]]
풀이법2
[[ 5.]
 [ 3.]
 [-2.]]
풀이법3
[[ 5.]
 [ 3.]
 [-2.]]


In [11]:
# 검산
5 + 3 + (-2)

6